### ISSUE TITLE
Broken attribute

### ISSUE THREAD

**Issue by BUTTOWSKIY** [DylanGiesberts/obsidian-table-checkboxes#3]
Hey! I really need this thing. But for some reason it doesn't work. I can put a checkbox in the table and it changes to HTML, but when I click on it the unchecked attribute doesn't change to checked. Maybe I did something wrong, or is it a bug at the moment

**Comment by thepancreator** [comment]
Having the same issue, checking the box doesn't change the HTML checkbox state

**Comment by DylanGiesberts** [comment]
See my response in #1
