### ISSUE TITLE
Checkboxes now functioning properly, but not inside of admonitions/quotes.

### ISSUE THREAD

**Issue by thepancreator** [DylanGiesberts/obsidian-table-checkboxes#5]
Thank you again for the recent update, I'm happy to say it's working in almost all cases now. However, when trying to create tabled checkboxes inside of an admonition/callout/quote, it no longer will convert the - [ ] into the HTML tag. If the tabled checkbox is written outside of the callout and then cut-and-pasted into the admonition, it functions as expected, but it can't be written directly in the callout.

**Comment by DylanGiesberts** [comment]
Thanks for reporting. Fixed in [2.0.1](https://github.com/DylanGiesberts/obsidian-table-checkboxes/releases/tag/2.0.1)
