### ISSUE TITLE
Auto check box

### ISSUE THREAD

**Issue by twestley** [DylanGiesberts/obsidian-table-checkboxes#7]
On both my Mac (14.1) and iPhone (iOS 17.0.3) using v2.04 of Markdown table checkboxes, with all checkboxes checked, unchecking a box automatically unchecks the one above or below. At any given time, I can only have one unchecked.

I used an editor and changed all the "checked" to "unchecked." On both now, checking the second one unchecks the first (first and second chronologically, not order in the file). At any given time, I can only have one checked. And so on.

Well, that's not strictly true, sometimes on the iPhone, the previous box stays checked when I check any other. I haven't figured out a pattern to get more than two boxes checked at the same time.

Using an editor outside Obsidian, I checked four (random, not sequential) boxes in a table of about 50 items. When opening Obsidian and that file from either Mac or iPhone, I still get the effect of checking a box unchecks another nearby. So now I can only have exactly four checked. And so on.

I used sort -u to verify that the ids in the file are unique, no duplicates.

**Comment by DylanGiesberts** [comment]
Hi thanks for reporting, I am able to reproduce it and will take a look later this week when I have time.

**Comment by DylanGiesberts** [comment]
Should be fixed in [2.0.5](https://github.com/DylanGiesberts/obsidian-table-checkboxes/releases/tag/2.0.5). Let me know if you run into any issues

**Comment by twestley** [comment]
Works great. Thanks.
